# Generated by Django 5.2 on 2025-05-02 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure', models.CharField(default='кг', verbose_name='Мера')),
            ],
            options={
                'verbose_name': 'Мера',
                'verbose_name_plural': 'Меры',
            },
        ),
        migrations.CreateModel(
            name='Product_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200, unique=True, verbose_name='Тип продукта')),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Типы',
            },
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.TextField(default='', verbose_name='Список продуктов')),
                ('status', models.BooleanField(default=True, verbose_name='Актуальность')),
                ('time', models.DateTimeField(default=None, verbose_name='Время покупки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='avatars/user-interface 1.png', upload_to='avatars/', verbose_name='Аватарка')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='Телефон')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название продукта')),
                ('description', models.TextField(verbose_name='Описание')),
                ('photo', models.ImageField(upload_to='products/', verbose_name='Фото')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Количество меры в 1 товаре')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('measure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organicapp.measure', verbose_name='Мера')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organicapp.product_type', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentary', models.TextField(verbose_name='Комментарий')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='Оценка')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organicapp.product', verbose_name='Продукт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
