# Generated by Django 5.2 on 2025-05-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organicapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='measure',
            field=models.CharField(verbose_name='Мера'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.FloatField(default=1.0, verbose_name='Количество меры в 1 товаре'),
        ),
    ]
