# Generated by Django 5.2 on 2025-05-02 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organicapp', '0002_alter_measure_measure_alter_product_quantity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_type',
            new_name='ProductType',
        ),
    ]
