# Generated by Django 5.2 on 2025-05-02 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organicapp', '0003_rename_product_type_producttype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measure',
            old_name='measure',
            new_name='measureName',
        ),
        migrations.RenameField(
            model_name='producttype',
            old_name='type',
            new_name='typeName',
        ),
    ]
