# Generated by Django 5.2 on 2025-05-07 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organicapp', '0004_rename_measure_measure_measurename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='products',
            field=models.TextField(default=dict, verbose_name='Список продуктов'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время покупки'),
        ),
        migrations.AlterField(
            model_name='info',
            name='avatar',
            field=models.ImageField(default='avatars/user-interface 1.png', upload_to='Avatars/', verbose_name='Аватарка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(upload_to='Products/', verbose_name='Фото'),
        ),
    ]
