# Generated by Django 5.2 on 2025-05-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organicapp', '0005_alter_basket_products_alter_basket_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='products',
            field=models.TextField(default={}, verbose_name='Список продуктов'),
        ),
    ]
