# Generated by Django 5.2 on 2025-05-08 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organicapp', '0006_alter_basket_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
    ]
