# Generated by Django 5.2 on 2025-05-09 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organicapp', '0008_alter_basket_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='phone',
        ),
    ]
