# Generated by Django 5.2 on 2025-05-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organicapp', '0009_remove_info_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='address',
            field=models.TextField(default='нет', verbose_name='Адрес'),
        ),
    ]
