# Generated by Django 5.2 on 2025-05-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organicapp', '0012_alter_info_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='address',
            field=models.TextField(default='', verbose_name='Адрес'),
        ),
    ]
